# Replace with location of your wallpaper

$wallpaper = ~/.config/arch_example_dotfiles/wallpapers/gruvbox/sailormoonpout_green.png

preload = $wallpaper
wallpaper = , $wallpaper
wallpaper = DP-1,$wallpaper,contain

splash = false

ipc = on # static or dynamic wallpaper
